### ISSUE TITLE
align_image_with_openpnm() does not work with non-cubic shapes

### ISSUE THREAD

**Issue by borahdj2010** [PMEAL/porespy-examples#3]
When the align_image_with_openpnm is used it aligns image with a rotation. This is not evident when a cubic domain is used. For example, when we use 
im = ps.generators.cylinders(shape=[300, 400, 500], radius=5, nfibers=200)
it generates a domain with 300 slices of size 400x500. The network extraction algorithm takes it as [X, Y, Z]. But the align function takes it as [Z, Y, X] i.e., the slices are stacked along the Z -direction. Thus the output looks like below:
![image](https://user-images.githubusercontent.com/24526540/41531018-55370272-72f2-11e8-92ff-5b054be7e386.png)

**Comment by jgostick** [comment]
Hmmm.....can you try this with blobs or another generated image?  I seem to recall the cylinders giving me problems with alignment...although once the image is generated it shouldn't matter.

**Comment by borahdj2010** [comment]
I tried with other image as well. I had some .RAW files from imageJ. These files were created by stacking µ-CT images. The stacked images were like (width) X (height) X (num. of slices) or WxHxD

I used the following codes to load the .RAW file

    im0 = np.fromfile(filename, dtype='uint8', sep='') 
    im = im0.reshape([DxHxW])

If i try to plot a slice now, it will show like below:
    plt.imshow(im[0, :, :])
![image](https://user-images.githubusercontent.com/24526540/41644999-00ca7c44-7470-11e8-817d-e3cc3ec28ca0.png)
The same behaviour is seen while using the following codes
    im = ps.generators.cylinders(shape=[300, 400, 500], radius=5, nfibers=400)
    plt.imshow(im[0, :, :]) 
![image](https://user-images.githubusercontent.com/24526540/41645229-a01c70ae-7470-11e8-869d-43be740095ae.png)

The rest is the standard process:

    dt = spim.distance_transform_edt(input=im)
    dt = spim.gaussian_filter(input=dt, sigma=0.4)
    peaks = ps.network_extraction.find_peaks(dt=dt, r=4)

    peaks = ps.network_extraction.trim_saddle_points(peaks=peaks, dt=dt)
    peaks = ps.network_extraction.trim_nearby_peaks(peaks=peaks, dt=dt)

    regions = ps.network_extraction.partition_pore_space(im=dt, peaks=peaks)
    net = ps.network_extraction.extract_pore_network(im=regions*im, 
                                                     dt=dt, voxel_size=voxel)
   
    mgr=op.Base.Workspace()
    pn = op.Network.GenericNetwork(name=net_name)
    pn.update(net)
    mgr.save_simulation(pn, filename=net_name)
    op.export_data(network=pn, filename=net_name, fileformat='VTK')
    ps.network_extraction.align_image_with_openpnm(im)
    imageio.mimsave(net_name+'.tif', sp.array(im, dtype=int))

But the outcome of overlaying network with image is the same as shown in the image below

![image](https://user-images.githubusercontent.com/24526540/41645477-6f31b4bc-7471-11e8-8164-e543c696882a.png)

**Comment by borahdj2010** [comment]
The same result is obtained if I try to overlay the .RAW file after converting to TIF in ImageJ. Maybe a transformation operation on the network will do the trick.

**Comment by jgostick** [comment]
ok...maybe there is a scipy/numpy/paraview version thing? Which versions of each you're using?  In the meantime, I'll check it on my system.

**Comment by jgostick** [comment]
The good news is I found the problem...the bad news is you're going to kick yourself firmly in the butt when you realize :-)

You didn't assign the output of the `align_image_with_openpnm` function back to `im`, so you just wrote the original image to file.

The second last line of your above code should be:

```
im = ps.network_extraction.align_image_with_openpnm(im)
```

**Comment by borahdj2010** [comment]
Thanks! I did!!
