### ISSUE TITLE
Can't show the tif picture

### ISSUE THREAD

**Issue by wangkeupc** [PMEAL/porespy-examples#4]
I run the code in the document 'snow_advanced' and 'snow_basic' of network_extraction. But the last tif picture show all black. Tiff of 3D soild aslo show all black and can't be visualized by paraview. I don't know the extract reason. Maybe it's the problem of imageio?

**Comment by jgostick** [comment]
Can you paste the code you're using to visualize the image?  Have you tried opening it in imagej and/or fiji?  Maybe you need to adjust the range of the image?  What is the max() and min()?

**Comment by wangkeupc** [comment]
The image can be visualized in imageJ. I download the latest version of paraview. And 2D image can be visualized in paraview successfully. So I think the version of paraview is important. 3D image of solid fiber can be imported into paraview, but it can only show the surface or slice. Maybe it's because my computer capacity is not enough or I did not follow the correct procedure in paraview.

**Comment by jgostick** [comment]
In paraview you need to apply a threshold to the image, so that only 1's are visible.  This should reveal the internal structure.
