### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by fjkr5** [PMEAL/porespy-examples#7]
Hello Dr. @jgostick ,

Sorry to bother you again. I tried to export the network by Porespy following this link https://github.com/PMEAL/porespy-examples/blob/master/network_extraction/snow_advanced.md
But it seems that you changed the functions, so I am not sure which one is the corresponding function. My colleagues don't know about it either. Can you please take a look of my problem? Attached is my code:

import porespy as ps
import matplotlib.pyplot as plt
import openpnm as op
import imageio
import scipy.ndimage as spim

im = ps.generators.cylinders(shape=[300, 300, 300], radius=5, ncylinders=200)
plt.imshow(ps.visualization.sem(im), cmap=plt.cm.bone)
plt.axis('off')

dt = spim.distance_transform_edt(input=im)
dt = spim.gaussian_filter(input=dt, sigma=0.4)
peaks = ps.filters.find_peaks(dt=dt, r_max=4)

regions = ps.networks.regions_to_network(im, dt=None, voxel_size=1)

plt.imshow((regions*im)[:, :, 100], cmap=plt.cm.spectral)
plt.axis('off')

pn = op.Network.GenericNetwork()
pn.update(net)
op.export_data(network=pn, filename='extracted_network', fileformat='VTK')

im = ps.network_extraction.align_image_with_openpnm(im)
imageio.mimsave('extracted_network.tif', sp.array(im, dtype=int))

In terminal, it returns:

Extracting pore and throat information from image
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00, -1.07it/s]
Traceback (most recent call last):
  File "ps.py", line 15, in <module>
    regions = ps.networks.regions_to_network(im, dt=None, voxel_size=1)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/porespy/networks/__getnet__.py", line 133, in regions_to_network
    PT1 = sp.sqrt(sp.sum(((p_coords[P12[:, 0]]-t_coords) * voxel_size)**2, axis=1))
IndexError: too many indices for array

Line 15 is 'regions = ps.networks.regions_to_network(im, dt=None, voxel_size=1)'

I know you are very busy so I appreciate any of your response. Thanks very much!

**Comment by jgostick** [comment]
I'm so sorry.  I didn't see the notification that you'd opened an issue. I gather that you solved your problem?

**Comment by fjkr5** [comment]
It's fine. The problem is solved. Thank you! ^_^
